// Generated by `bun init`

declare module "*.svg" {
	/**
	 * A path to the SVG file
	 */
	const path: `${string}.svg`;
	export default path;
}

declare module "*.css" {
	/**
	 * A path to the CSS file
	 */
	const path: `${string}.css`;
	export default path;
}

declare module "*.module.css" {
	/**
	 * A record of class names to their corresponding CSS module classes
	 */
	const classes: { readonly [key: string]: string };
	export default classes;
}
